### ISSUE TITLE
Expose setting custom headers for getFileContent (and other request methods)

### ISSUE THREAD

**Issue by dghelm** [SkynetLabs/skynet-js#117]
Right now, skynet-js doesn't allow setting arbitrary headers on client requests for methods like getFileContent.

We should either expose adding `headers` as an option in CustomDownloadOptions, or look into adding `range` if full access to headers is too unfriendly of an API.

**Comment by m-cat** [comment]
Would `range` just take a string? I'm not sure whet the format of that header is supposed to be.

**Comment by dghelm** [comment]
Yes, since the syntax can vary depending on the use case, but is passed in the header as a string.
For reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range#syntax

**Comment by m-cat** [comment]
That sounds good to me. I will implement `range` as a custom option, instead of allowing arbitrary headers, for now.
