### ISSUE TITLE
Do not allow passing both `dev` and `alpha` options for MySky

### ISSUE THREAD

**Issue by m-cat** [SkynetLabs/skynet-js#257]
Setting both should not be allowed. One sends you to the URL for alpha MySky and the other to dev MySky at a different URL. They are incompatible so if you try passing both it should be an error.

**Comment by m-cat** [comment]
https://github.com/SkynetLabs/skynet-js/pull/254#discussion_r691005321

**Comment by kwypchlo** [comment]
closed by https://github.com/SkynetLabs/skynet-js/pull/352
