### ISSUE TITLE
getSkylinkUrl with subdomain: true doesn't work from base32 skapps

### ISSUE THREAD

**Issue by MSevey** [SkynetLabs/skynet-js#4]
<a href="https://github.com/m-cat"><img src="https://avatars.githubusercontent.com/u/6035856?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [m-cat](https://github.com/m-cat)**
_Thursday Feb 11, 2021 at 15:34 GMT_
_Originally opened as https://github.com/NebulousLabs/skynet-js/issues/303_

----

Example:

My skapp `https://vg4hm678pvjltuh5nmmfimdi9jud7tggoda3eo4651uioqrii5oali0.siasky.net` calls `getSkylinkUrl("_AkeLeS84huwnOKEdP9o36dE1qJkmwHCVpzyFcMhv5d33A", { subdomain: true })`

The result is `https://vg4o10vtuj8j5np6rm4ujohmpaoksi9f9ei5ecnkguch74qgepbiobg.vg4hm678pvjltuh5nmmfimdi9jud7tggoda3eo4651uioqrii5oali0.siasky.net/`.

The expected result is `https://vg4o10vtuj8j5np6rm4ujohmpaoksi9f9ei5ecnkguch74qgepbiobg.siasky.net/`.

This is probably impossible until https://github.com/NebulousLabs/skynet-webportal/issues/423 is implemented.

**Comment by m-cat** [comment]
This is confirmed to be fixed.
