### ISSUE TITLE
Ask for helpful feature for compatibility, changes in package.json for developers.

### ISSUE THREAD

**Issue by parajbs** [SkynetLabs/skynet-js#468]
hello **skynet-js developer**,

Sorry about the title but I had no other idea for the title.

I'm trying to extend your repo "**SkynetLabs/nodejs-skynet**" with functions of "**SkynetLabs/skynet-js**" and make them compatible.

For the integration of the functions in "nodejs-skynet", it would be **very helpful** if I could access the **original variables and functions**.
**It would also be easier to handle if there are changes in "skynet-js" in the future.**

Here is my idea, so that you have access to all original variables and also original functions, which are exported from "skynet-js".

To do this, I inserted a few lines in the "**package.json**" of "**SkynetLabs/skynet-js**" in the "**exports**" area, and I was able to convert any original variable from "**skynet-js**" **to** "**nodejs-skynet**" to integrate with "require".

**1. "exports" before:**

  "exports": {
    ".": {
      "import": "./dist/mjs/index.js",
      "require": "./dist/cjs/index.js"
    }

**2. "exports" my new:**

  "exports": {
    ".": {
      "import": "./dist/mjs/index.js",
      "require": "./dist/cjs/index.js"
    },
    "./\*": "./dist/cjs/\*.js",
    "./mysky/\*": "./dist/cjs/mysky/\*.js",
    "./skylink/\*": "./dist/cjs/skylink/\*.js",
    "./utils/\*": "./dist/cjs/utils/\*.js"
  },

It definitely works!

Would be very, very helpful, and a cool feature too.
You could then create better apps for the command line.

I would be happy if you integrate it. But I can also create a PR for the few lines, but only if you want it.

**Let me know what you think of it.**

**Comment by parajbs** [comment]
hello m-cat

I already have a version where I'm testing new functions, such as:

nodejs_db_setJSONencrypt
nodejs_db_getJSONdecrypt

Where you can encrypt/decrypt the JsonData with "nacl.sign" from "tweetnacl", but with an "APPSecretSeed" so that the data is encrypted on Skynet, and can only be decrypted with the "APPSecretSeed".
But I didn't like it yet, I saw that in the "skynet-js" code that you also use the same components in "mysky", but a little differently than I had thought for my new functions.
In order for the function to be compatible, I tried to import it and not port it. But there was no way.

That's why I made the request to "skynet-js".
But also to simplify the development here in "nodejs-skynet".

I didn't quite understand the number 2.
Backward compatibility is important. But I don't understand what the change should trigger and why it's no longer backwards compatible.
I see it more as a new feature, and of course you can only get new features with a new version. This doesn't bother me in any way.

I installed it myself to test it extensively.
There haven't been any errors yet. But will continue to test.

It would also be helpful to get the "mysky" function in "nodejs-skynet".
And for other functions that we want to integrate.

So I think it makes sense to change this or in a smaller version.

But I think you know your code better than me.

**Comment by m-cat** [comment]
I see. Can you make a list of what you need to implement `get/setJSONEncrypted`, so I can consider whether it makes sense to export those things?

> Backward compatibility is important. But I don't understand what the change should trigger and why it's no longer backwards compatible.

We would be committing to keeping backwards compatibility for anything we export. A lot of those things are internal implementation details, and haven't had the same rigor in API design and consistency as the things we exported. Some of the internal stuff can change or be swapped out at any time e.g. if we changed out a dependency. So we are exposing things on an as-needed basis; if there is something in the code you think would be helpful, let me know and I'll consider it.

**Comment by parajbs** [comment]
hello m-cat

I already have two working versions of "getJSONdecrypted/setJSONencrypted" with "tweetnacl" and the keys are generated with "genKeyPairFromSeed" of "skynet-js".

For the first two versions I used "**nacl.sign**" and "**nacl.sign.open**".
On the internet someone gave me an info and tip it would be better
to use "**nacl.secretbox**" and "**nacl.secretbox.open**". So I will try to make a third version.
I saw "secretbox" and "secretbox.open" being used in "skynet-js".

I have seen that there are also "**nacl.box**" and "**nacl.box.open**". That means I could also create a fourth version.

**I just have to think about it and we have to decide in which format (e.g.: base64 or other) the encrypted data should be uploaded to skynet.
And whether the data on Skynet should be decryptable with a third-party app, so that the skylink can be downloaded and then decrypted on the client pc with a third-party app. Let's see**.

Oh, I didn't make the request directly because of these "getJSONdecrypted/setJSONencrypted" functions, I actually wanted to integrate "loadMySky".
I had several problems with the integration, since I saw that "mysky" has a subfolder, and thought I'd approach the problems a little differently than usual.
I then wanted to port "loadMySky" and would have needed some original variables.
But I gave up and put it back.
I don't think it's that important anymore for the time being, because I always find the backwards compatibility of apps important and because you offered me to let me know if I might need things to establish compatibility.
I'll let you know when I have a new suggestion.

Thanks.
I think you can close here.

**Comment by m-cat** [comment]
> I think you can close here.

Sure, thanks as always for the issue. 👍
