### ISSUE TITLE
4.0.0-beta breaks resolveHNS

### ISSUE THREAD

**Issue by dghelm** [SkynetLabs/skynet-js#47]
We should discuss how this works. With Skylinks v2, an HNS address might be set to a mutable link that points to a mutable link (and so on) until it resolves to an immutable skylink.

I think we should consider returning and an object of both what the HNS points to (ie it's DNS TXT record) and then where link eventually resolves (the skylink that would be served by the browser when visiting that first pointer).

**Comment by m-cat** [comment]
This has since been fixed.
