### ISSUE TITLE
small bug found in the documentation on "sdk.skynetlabs.com"

### ISSUE THREAD

**Issue by parajbs** [SkynetLabs/skynet-js#471]
Hello developers,

I have in the "sdk.skynetlabs.com" under these links:

https://sdk.skynetlabs.com/v4/?javascript--browser#uploading-a-file
other
https://sdk.skynetlabs.com/v4/?javascript--browser#uploading-a-directory

At the point "uploading-a-file" and "uploading-a-directory", each in the sub-point "Response" in the documentation stands for:

  "BrowserJS":
"sia:CABAB_1Dt0FJsxqsu_J4TodNCbCGvtFf1Uys_3EgzOlTcg"

e.g. "NodeJS":
"sia://CABAB_1Dt0FJsxqsu_J4TodNCbCGvtFf1Uys_3EgzOlTcg"

I think the "Browser JS" version is missing two "//" after "sia:" , it should look like this:
"sia://CABAB_1Dt0FJsxqsu_J4TodNCbCGvtFf1Uys_3EgzOlTcg"

It's a little confusing when you're new.

**Comment by m-cat** [comment]
Done!
