### ISSUE TITLE
How to use with Vite?

### ISSUE THREAD

**Issue by Bellisario** [SkynetLabs/skynet-js#527]
I wanted to try using with Vite, but seems there is a console error:

```
Uncaught ReferenceError: global is not defined
    at node_modules/randombytes/browser.js (browser.js:16:14)
    at __require2 (chunk-ASBRWZGP.js?v=88b69488:15:50)
    at crypto.js:3:25
```

Looking the error, seems the randombytes module is not able to get browser `global.crypto` because it is using `global` instead of `globalThis`.

Any solution?

**Comment by Bellisario** [comment]
Solved this issue by adding a new script tag to HTML page (on the head) with this content:
```js
const global = window
```

**Comment by m-cat** [comment]
Cool, glad it's solved for you. Thanks for bringing it up - might help someone else!
