### ISSUE TITLE
Can you publish version 4.3 on "https://skynet-js.hns.siasky.net/"?

### ISSUE THREAD

**Issue by parajbs** [SkynetLabs/skynet-js#528]
Hello skynet-js support team,

I'm not sure who owns the hns domain "https://skynet-js.hns.siasky.net/", so I'm contacting you here.

Can you publish version 4.3 of "skynet-js" there on "https://skynet-js.hns.siasky.net/".
At the moment there is only version 4.1 of "skynet-js".

Would be cool, because if I make my own version of 4.1 and then compare it, it looks different, but it works.

Or can you publish the webpack script so that I can create my own version like you.

Thanks in advance.

**Comment by parajbs** [comment]
Hello m-cat,

Thank you for providing the new version 4.3.
It helps me, so I can do the online test again.
I often test things online with "jsbin" or "jsfiddle".
That will work again.

Thanks

**Comment by m-cat** [comment]
No problem @parajbs. I'm still working on publishing a script for this, had to get a new nodejs version out first.
