### ISSUE TITLE
Migrate SDK to never assume skynet-file-metadata

### ISSUE THREAD

**Issue by dghelm** [SkynetLabs/skynet-js#77]
New upload types will be dropping "skynet-file-metadata" from default inclusion.

We will want to call the new portal endpoint (not use a HEAD request) for `getMetadata`. Also, we will want to include skynet-file-metadata information only when an explicit "enable" option is enabled. This new opt-in default will avoid 2 network requests for these calls.

**Comment by m-cat** [comment]
What is the portal endpoint? What is the enable option called?

**Comment by dghelm** [comment]
I don't think we have an endpoint for actually implementing this yet, so we can keep the HEAD request for now, but as a default, any client settings should default to "false" for returning skynet-file-metadata. Similarly, we should not return that field in any method returns unless the option is set to true.

**Comment by dghelm** [comment]
The skyd API commit is here:
https://gitlab.com/SkynetLabs/skyd/-/merge_requests/120/diffs?commit_id=d6d52387c65c426388e3afb052f055267c4965f5

Will post info about behavior specifics once I hear back.

**Comment by m-cat** [comment]
@dghelm Has this been resolved with the recent metadata changes? We now call the new GET endpoint, but we did not add an enable option.

**Comment by dghelm** [comment]
Yup!

I think I meant to say that in the context of getFileContent, but I can't imagine why a dev would prefer that in 1 JS method over 2, since it's inherently 2 HTTP requests.
